name: fluit
description: Flutter animation studio
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.4.0
  flutter: ^3.22.0

dependencies:
  collection: ^1.18.0
  dart_style: ^2.3.6
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  mustache_template: ^2.0.0
  state_beacon: ^1.0.0
  syntax_highlight: ^0.4.0
  uuid: ^4.4.2

dev_dependencies:
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/translations/
    - assets/translations/en.json
